apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emqx
subjects:
  - kind: ServiceAccount
    name: emqx
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
    - port: 32333
      nodePort: 32333
      targetPort: emqx-dashboard
      protocol: TCP
  selector:
    app: emqx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-mqtt
spec:
  ports:
    - port: 32334
      nodePort: 32334
      targetPort: emqx-mqtt
      protocol: TCP
  selector:
    app: emqx
  type: NodePort
---

---
apiVersion: v1
kind: Service
metadata:
  name: emqx-mqtt-ssl
spec:
  ports:
    - port: 32335
      nodePort: 32335
      targetPort: emqx-mqtt-ssl
      protocol: TCP
  selector:
    app: emqx
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-secrets
data:
  key.pem: #Here
  cert.pem: #Here
  cacert.pem: #Here
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: emqx
    spec:
      serviceAccountName: emqx
      containers:
        - name: emqx
          image: emqx/emqx:latest
          volumeMounts:
            - mountPath: "/opt/emqx/etc/certs"
              name: cert-volume
              readOnly: true
          ports:
            - name: emqx-dashboard
              containerPort: 18083
            - name: emqx-http
              containerPort: 8083
            - name: emqx-mqtt
              containerPort: 1883
            - name: emqx-mqtt-ssl
              containerPort: 8883
          env:
            - name: EMQX_ALLOW_ANONYMOUS
              value: "false"
            - name: EMQX_CLUSTER__DISCOVERY
              value: k8s
            - name: EMQX_NAME
              value: emqx
            - name: EMQX_CLUSTER__K8S__APISERVER
              value: https://kubernetes.default:443
            - name: EMQX_CLUSTER__K8S__NAMESPACE
              value: default
            - name: EMQX_CLUSTER__K8S__SERVICE_NAME
              value: emqx
            - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
              value: ip
            - name: EMQX_CLUSTER__K8S__APP_NAME
              value: emqx
            - name: EMQX_LOADED_PLUGINS
              value: emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_pgsql
            - name: EMQX_AUTH__PGSQL__SERVER
              value: psql-db-svc.default.svc:5432
            - name: EMQX_AUTH__PGSQL__USERNAME
              value: docker
            - name: EMQX_AUTH__PGSQL__PASSWORD
              value: docker
            - name: EMQX_AUTH__PGSQL__DATABASE
              value: mqtt_db
            - name: EMQX_AUTH__PGSQL__PASSWORD_HASH
              value: salt,bcrypt
            - name: EMQX_AUTH__PGSQL__AUTH_QUERY
              value: select password, substring(password, 0, 30) as salt from mqtt_user where username = '%u' limit 1
            - name: EMQX_LOG__LEVEL
              value: debug
            - name: EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE
              value: "{{ platform_etc_dir }}/certs/cacert.pem"
          tty: true
      volumes:
        - name: cert-volume
          secret:
            secretName: cert-secrets
